
# ===========================================
# General Settings
# ===========================================

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = false
#opacity = 0.80
opacity = 0.87
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6


# ===========================================
#    Color Scheme
# ===========================================

# Current Catppucen-mocha
[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#EF9F76"
index = 16

[[colors.indexed_colors]]
color = "#F2D5CF"
index = 17

[colors.bright]
black = "#626880"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#A5ADCE"
yellow = "#E5C890"

[colors.cursor]
cursor = "#F2D5CF"
text = "#303446"

[colors.dim]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[colors.hints.end]
background = "#A5ADCE"
foreground = "#303446"

[colors.hints.start]
background = "#E5C890"
foreground = "#303446"

[colors.normal]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[colors.primary]
background = "#303446"
bright_foreground = "#C6D0F5"
dim_foreground = "#C6D0F5"
foreground = "#C6D0F5"

[colors.search.focused_match]
background = "#A6D189"
foreground = "#303446"

# [colors.search.footer_bar]
# background = "#A5ADCE"
# foreground = "#303446"

[colors.search.matches]
background = "#A5ADCE"
foreground = "#303446"

[colors.selection]
background = "#F2D5CF"
text = "#303446"

[colors.vi_mode_cursor]
cursor = "#BABBF1"
text = "#303446"


# ===========================================
#   font settings
# ===========================================

[font]
size = 11.5

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Bold"

[font.offset]
x = 0
y = 1


# ===========================================
#   Key Binds
# ===========================================

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 5000

# ===========================================
#   Other color schemes
# ===========================================

# [[schemes.Catppuccin-Frappe.indexed_colors]]
# color = "#EF9F76"
# index = 16
#
# [[schemes.Catppuccin-Frappe.indexed_colors]]
# color = "#F2D5CF"
# index = 17
#
# [schemes.Catppuccin-Frappe.bright]
# black = "#626880"
# blue = "#8CAAEE"
# cyan = "#81C8BE"
# green = "#A6D189"
# magenta = "#F4B8E4"
# red = "#E78284"
# white = "#A5ADCE"
# yellow = "#E5C890"
#
# [schemes.Catppuccin-Frappe.cursor]
# cursor = "#F2D5CF"
# text = "#303446"
#
# [schemes.Catppuccin-Frappe.dim]
# black = "#51576D"
# blue = "#8CAAEE"
# cyan = "#81C8BE"
# green = "#A6D189"
# magenta = "#F4B8E4"
# red = "#E78284"
# white = "#B5BFE2"
# yellow = "#E5C890"
#
# [schemes.Catppuccin-Frappe.hints.end]
# background = "#A5ADCE"
# foreground = "#303446"
#
# [schemes.Catppuccin-Frappe.hints.start]
# background = "#E5C890"
# foreground = "#303446"
#
# [schemes.Catppuccin-Frappe.normal]
# black = "#51576D"
# blue = "#8CAAEE"
# cyan = "#81C8BE"
# green = "#A6D189"
# magenta = "#F4B8E4"
# red = "#E78284"
# white = "#B5BFE2"
# yellow = "#E5C890"
#
# [schemes.Catppuccin-Frappe.primary]
# background = "#303446"
# bright_foreground = "#C6D0F5"
# dim_foreground = "#C6D0F5"
# foreground = "#C6D0F5"
#
# [schemes.Catppuccin-Frappe.search.focused_match]
# background = "#A6D189"
# foreground = "#303446"
#
# [schemes.Catppuccin-Frappe.search.footer_bar]
# background = "#A5ADCE"
# foreground = "#303446"
#
# [schemes.Catppuccin-Frappe.search.matches]
# background = "#A5ADCE"
# foreground = "#303446"
#
# [schemes.Catppuccin-Frappe.selection]
# background = "#F2D5CF"
# text = "#303446"
#
# [schemes.Catppuccin-Frappe.vi_mode_cursor]
# cursor = "#BABBF1"
# text = "#303446"
#
# [[schemes.Catppuccin-Macchiato.indexed_colors]]
# color = "#F5A97F"
# index = 16
#
# [[schemes.Catppuccin-Macchiato.indexed_colors]]
# color = "#F4DBD6"
# index = 17
#
# [schemes.Catppuccin-Macchiato.bright]
# black = "#5B6078"
# blue = "#8AADF4"
# cyan = "#8BD5CA"
# green = "#A6DA95"
# magenta = "#F5BDE6"
# red = "#ED8796"
# white = "#A5ADCB"
# yellow = "#EED49F"
#
# [schemes.Catppuccin-Macchiato.cursor]
# cursor = "#F4DBD6"
# text = "#24273A"
#
# [schemes.Catppuccin-Macchiato.dim]
# black = "#494D64"
# blue = "#8AADF4"
# cyan = "#8BD5CA"
# green = "#A6DA95"
# magenta = "#F5BDE6"
# red = "#ED8796"
# white = "#B8C0E0"
# yellow = "#EED49F"
#
# [schemes.Catppuccin-Macchiato.hints.end]
# background = "#A5ADCB"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.hints.start]
# background = "#EED49F"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.normal]
# black = "#494D64"
# blue = "#8AADF4"
# cyan = "#8BD5CA"
# green = "#A6DA95"
# magenta = "#F5BDE6"
# red = "#ED8796"
# white = "#B8C0E0"
# yellow = "#EED49F"
#
# [schemes.Catppuccin-Macchiato.primary]
# background = "#24273A"
# bright_foreground = "#CAD3F5"
# dim_foreground = "#CAD3F5"
# foreground = "#CAD3F5"
#
# [schemes.Catppuccin-Macchiato.search.focused_match]
# background = "#A6DA95"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.search.footer_bar]
# background = "#A5ADCB"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.search.matches]
# background = "#A5ADCB"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.selection]
# background = "#F4DBD6"
# text = "#24273A"
#
# [schemes.Catppuccin-Macchiato.vi_mode_cursor]
# cursor = "#B7BDF8"
# text = "#24273A"
#
# [[schemes.Catppuccin-Mocha.indexed_colors]]
# color = "#FAB387"
# index = 16
#
# [[schemes.Catppuccin-Mocha.indexed_colors]]
# color = "#F5E0DC"
# index = 17
#
# [schemes.Catppuccin-Mocha.bright]
# black = "#585B70"
# blue = "#89B4FA"
# cyan = "#94E2D5"
# green = "#A6E3A1"
# magenta = "#F5C2E7"
# red = "#F38BA8"
# white = "#A6ADC8"
# yellow = "#F9E2AF"
#
# [schemes.Catppuccin-Mocha.cursor]
# cursor = "#F5E0DC"
# text = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.dim]
# black = "#45475A"
# blue = "#89B4FA"
# cyan = "#94E2D5"
# green = "#A6E3A1"
# magenta = "#F5C2E7"
# red = "#F38BA8"
# white = "#BAC2DE"
# yellow = "#F9E2AF"
#
# [schemes.Catppuccin-Mocha.hints.end]
# background = "#A6ADC8"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.hints.start]
# background = "#F9E2AF"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.normal]
# black = "#45475A"
# blue = "#89B4FA"
# cyan = "#94E2D5"
# green = "#A6E3A1"
# magenta = "#F5C2E7"
# red = "#F38BA8"
# white = "#BAC2DE"
# yellow = "#F9E2AF"
#
# [schemes.Catppuccin-Mocha.primary]
# background = "#1E1E2E"
# bright_foreground = "#CDD6F4"
# dim_foreground = "#CDD6F4"
# foreground = "#CDD6F4"
#
# [schemes.Catppuccin-Mocha.search.focused_match]
# background = "#A6E3A1"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.search.footer_bar]
# background = "#A6ADC8"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.search.matches]
# background = "#A6ADC8"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.selection]
# background = "#F5E0DC"
# text = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.vi_mode_cursor]
# cursor = "#B4BEFE"
# text = "#1E1E2E"
#
# [schemes.DoomOne.bright]
# black = "#5b6268"
# blue = "#3071db"
# cyan = "#46d9ff"
# green = "#4db5bd"
# magenta = "#a9a1e1"
# red = "#da8548"
# white = "#dfdfdf"
# yellow = "#ecbe7b"
#
# [schemes.DoomOne.cursor]
# cursor = "#528bff"
# text = "CellBackground"
#
# [schemes.DoomOne.normal]
# black = "#1c1f24"
# blue = "#51afef"
# cyan = "#5699af"
# green = "#98be65"
# magenta = "#c678dd"
# red = "#ff6c6b"
# white = "#abb2bf"
# yellow = "#da8548"
#
# [schemes.DoomOne.primary]
# background = "#282c34"
# foreground = "#bbc2cf"
#
# [schemes.DoomOne.selection]
# background = "#3e4451"
# text = "CellForeground"
#
# [schemes.Dracula.bright]
# black = "#4d4d4d"
# blue = "#caa9fa"
# cyan = "#9aedfe"
# green = "#5af78e"
# magenta = "#ff92d0"
# red = "#ff6e67"
# white = "#e6e6e6"
# yellow = "#f4f99d"
#
# [schemes.Dracula.cursor]
# cursor = "CellForeground"
# text = "CellBackground"
#
# [schemes.Dracula.dim]
# black = "#14151b"
# blue = "#4d5b86"
# cyan = "#59dffc"
# green = "#1ef956"
# magenta = "#ff46b0"
# red = "#ff2222"
# white = "#e6e6d1"
# yellow = "#ebf85b"
#
# [schemes.Dracula.line_indicator]
# background = "None"
# foreground = "None"
#
# [schemes.Dracula.normal]
# black = "#000000"
# blue = "#bd93f9"
# cyan = "#8be9fd"
# green = "#50fa7b"
# magenta = "#ff79c6"
# red = "#ff5555"
# white = "#bfbfbf"
# yellow = "#f1fa8c"
#
# [schemes.Dracula.primary]
# background = "#282a36"
# foreground = "#f8f8f2"
#
# [schemes.Dracula.search.focused_match]
# background = "#ffb86c"
# foreground = "#44475a"
#
# [schemes.Dracula.search.matches]
# background = "#50fa7b"
# foreground = "#44475a"
#
# [schemes.Dracula.selection]
# background = "#44475a"
# text = "CellForeground"
#
# [schemes.Dracula.vi_mode_cursor]
# cursor = "CellForeground"
# text = "CellBackground"
#
# [schemes.GruvboxDark.bright]
# black = "#928374"
# blue = "#83a598"
# cyan = "#8ec07c"
# green = "#b8bb26"
# magenta = "#d3869b"
# red = "#fb4934"
# white = "#ebdbb2"
# yellow = "#fabd2f"
#
# [schemes.GruvboxDark.normal]
# black = "#282828"
# blue = "#458588"
# cyan = "#689d6a"
# green = "#98971a"
# magenta = "#b16286"
# red = "#cc241d"
# white = "#a89984"
# yellow = "#d79921"
#
# [schemes.GruvboxDark.primary]
# background = "#282828"
# foreground = "#ebdbb2"
#
# [schemes.MonokaiPro.bright]
# black = "#727072"
# blue = "#FC9867"
# cyan = "#78DCE8"
# green = "#A9DC76"
# magenta = "#AB9DF2"
# red = "#FF6188"
# white = "#FCFCFA"
# yellow = "#FFD866"
#
# [schemes.MonokaiPro.normal]
# black = "#403E41"
# blue = "#FC9867"
# cyan = "#78DCE8"
# green = "#A9DC76"
# magenta = "#AB9DF2"
# red = "#FF6188"
# white = "#FCFCFA"
# yellow = "#FFD866"
#
# [schemes.MonokaiPro.primary]
# background = "#2D2A2E"
# foreground = "#FCFCFA"
#
# [schemes.Nord.bright]
# black = "#4C566A"
# blue = "#81A1C1"
# cyan = "#8FBCBB"
# green = "#A3BE8C"
# magenta = "#B48EAD"
# red = "#BF616A"
# white = "#ECEFF4"
# yellow = "#EBCB8B"
#
# [schemes.Nord.normal]
# black = "#3B4252"
# blue = "#81A1C1"
# cyan = "#88C0D0"
# green = "#A3BE8C"
# magenta = "#B48EAD"
# red = "#BF616A"
# white = "#E5E9F0"
# yellow = "#EBCB8B"
#
# [schemes.Nord.primary]
# background = "#2E3440"
# foreground = "#D8DEE9"
#
# [schemes.OceanicNext.bright]
# black = "#343d46"
# blue = "#6699cc"
# cyan = "#5fb3b3"
# green = "#99C794"
# magenta = "#c594c5"
# red = "#EC5f67"
# white = "#d8dee9"
# yellow = "#FAC863"
#
# [schemes.OceanicNext.cursor]
# cursor = "#ffffff"
# text = "#1b2b34"
#
# [schemes.OceanicNext.normal]
# black = "#343d46"
# blue = "#6699cc"
# cyan = "#5fb3b3"
# green = "#99C794"
# magenta = "#c594c5"
# red = "#EC5f67"
# white = "#d8dee9"
# yellow = "#FAC863"
#
# [schemes.OceanicNext.primary]
# background = "#1b2b34"
# foreground = "#d8dee9"
#
# [schemes.Palenight.bright]
# black = "#434758"
# blue = "#9cc4ff"
# cyan = "#a3f7ff"
# green = "#ddffa7"
# magenta = "#e1acff"
# red = "#ff8b92"
# white = "#ffffff"
# yellow = "#ffe585"
#
# [schemes.Palenight.normal]
# black = "#292d3e"
# blue = "#82aaff"
# cyan = "#89ddff"
# green = "#c3e88d"
# magenta = "#c792ea"
# red = "#f07178"
# white = "#d0d0d0"
# yellow = "#ffcb6b"
#
# [schemes.Palenight.primary]
# background = "#292d3e"
# foreground = "#d0d0d0"
#
# [schemes.SolarizedDark.bright]
# black = "#002b36"
# blue = "#839496"
# cyan = "#93a1a1"
# green = "#586e75"
# magenta = "#6c71c4"
# red = "#cb4b16"
# white = "#fdf6e3"
# yellow = "#657b83"
#
# [schemes.SolarizedDark.cursor]
# cursor = "#839496"
# text = "#002b36"
#
# [schemes.SolarizedDark.normal]
# black = "#073642"
# blue = "#268bd2"
# cyan = "#2aa198"
# green = "#859900"
# magenta = "#d33682"
# red = "#dc322f"
# white = "#eee8d5"
# yellow = "#b58900"
#
# [schemes.SolarizedDark.primary]
# background = "#002b36"
# foreground = "#839496"
#
# [schemes.SolarizedLight.bright]
# black = "#002b36"
# blue = "#839496"
# cyan = "#93a1a1"
# green = "#586e75"
# magenta = "#6c71c4"
# red = "#cb4b16"
# white = "#fdf6e3"
# yellow = "#657b83"
#
# [schemes.SolarizedLight.cursor]
# cursor = "#657b83"
# text = "#fdf6e3"
#
# [schemes.SolarizedLight.normal]
# black = "#073642"
# blue = "#268bd2"
# cyan = "#2aa198"
# green = "#859900"
# magenta = "#d33682"
# red = "#dc322f"
# white = "#eee8d5"
# yellow = "#b58900"
#
# [schemes.SolarizedLight.primary]
# background = "#fdf6e3"
# foreground = "#657b83"
#
# [schemes.TomorrowNight.bright]
# black = "#666666"
# blue = "#81a2be"
# cyan = "#54ced6"
# green = "#9ec400"
# magenta = "#b77ee0"
# red = "#ff3334"
# white = "#282a2e"
# yellow = "#f0c674"
#
# [schemes.TomorrowNight.cursor]
# cursor = "#ffffff"
# text = "#1d1f21"
#
# [schemes.TomorrowNight.normal]
# black = "#1d1f21"
# blue = "#81a2be"
# cyan = "#70c0ba"
# green = "#b5bd68"
# magenta = "#b294bb"
# red = "#cc6666"
# white = "#373b41"
# yellow = "#e6c547"
#
# [schemes.TomorrowNight.primary]
# background = "#1d1f21"
# foreground = "#c5c8c6"
#
